### ISSUE TITLE
App not working for me

### ISSUE THREAD

**Issue by jk1993** [Delubear/GlucoseTray#37]
I initially thought it was a newer version that I updated to but now I can't get any version working at all. I'm not getting any error messages, I've cleared the temp directory but not sure where to look for logs. Basically nothing happens when the app opens. Windows 10 with all the latest updates.

Any suggestions?

Thanks

**Comment by sgmoore** [comment]
What version of .Net Framework are you using? I think the very latest version of GlucoseTray may need .Net 5.0

I guess I would start by looking in the Windows Event Log.

Other than a framework error, I would suspect a missing or corrupt appsettings.json file and in both those cases you should see it recorded in the Application Event log.

Otherwise open the appsettings.json file and check your entry for DatabaseLocation and then see if this database has been created.  If it has been created, you will need some way of opening this database to see the log files. It is a sqlite database and you can open it for example in LinqPad 6. (If that is too much trouble and you aren't too worried about privacy you could upload the database here. If you haven't got this working previously then there should not be no glucose readings, but it is possible the logs may contain personal information such as your nightscout url, or directory names).

**Comment by jk1993** [comment]
Thanks - will try upgrading .Net and will have a look in the Event Log. I think I deleted the database file as an attempt to start fresh but that could have messed things up more and could even be why it's not starting now since no new database is being created when I run the program.

**Comment by jk1993** [comment]
Had a look in the logs and was getting this:

```Message: Error:
  An assembly specified in the application dependencies manifest (GlucoseTrayCore.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '5.0.0'
    path: 'clrcompression.dll'
```
Installed the latest .Net and no difference, so restarted Windows and still nothing, same error.

Not sure what to try next as I'm not sure what the compression package missing is.

**Comment by sgmoore** [comment]
That looks like an issue with generating the release version as opposed to the actual source code. (It should be including all the parts of the framework that are needed, but is missing quite a few). 

You could try version 8.4.1 which should be functionally the same but targets .Net Core 3.1 rather than 5.0, but appears to work.

**Comment by jk1993** [comment]
I have tried version 8.4.1 and get a different error:
```
Message: Error:
  An assembly specified in the application dependencies manifest (GlucoseTrayCore.deps.json) was not found:
    package: 'Microsoft.Bcl.AsyncInterfaces', version: '1.1.1'
    path: 'lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.dll'
```

**Comment by sgmoore** [comment]
I've submitted a patch which hopefully will fix this issue. You'll need to wait for Chris to check it out, but if you want to test it you can download it from [https://we.tl/t-BrTrIm4zRc](https://we.tl/t-BrTrIm4zRc) (which is WeTransfer and should be available for 7 days).

It works for me, but then again 8.4.1 worked for me as well!.

**Comment by jk1993** [comment]
Seems to be working for me! Thanks

**Comment by Delubear** [comment]
PR approved.  Thank you
