### ISSUE TITLE
Fix - Handle Nightscout URLs ending with a /

### ISSUE THREAD

**Issue by Delubear** [Delubear/GlucoseTray#53]
Automatically handle if a user enters their nightscout URL with an ending "/".

This just caused me some headache.

**Comment by dacia1300** [comment]
Hello 
Please note that this issue still occurs. 
I installed it on Windows 10. I copy and pasted my Nightscout url in Settings  and forgot to delete the / at the end.
The popup with Do you want to import readings from Nightscout appeared and I chose Yes. 
Nothing happens afterwards. The app does nothing.
After Deleting and re-downloading the app only the popup re-appears due to the settings file still being present in Appdata>Roaming.
It took me a while to find it and delete the GlucoseTrayCore file from Appdata so that the Settings section re-appears again.
Can you add in the wiki the steps to resolve this issue?
Something easy to follow like:
1. Click Start.
2. Write  %appdata% 
3. Delete GlucoseTrayCore folder

Also is it possible to add a setting for the Font size that appears in the taskbar? 
Currently it is extremely small and hard to notice. 
Thanks for a great app.

**Comment by Delubear** [comment]
There was actually two fixes put in place for this, since I didn't notice the pending pull request.  Version 11.1.3 should now handle trailing / breaking nightscout usage.

Font size is really difficult, as Windows doesn't give you a lot to work with as far as tray icons go.  And we have to fit up to 3 numbers and sometimes a decimal if we're using ML.  So the text can't be really made any larger without becoming unreadable.  At least in all the testing and experimenting i've done.
