### ISSUE TITLE
Criticle low glucose warning every ~minute without numbers

### ISSUE THREAD

**Issue by derTheo01** [Delubear/GlucoseTray#68]
For a couple of weeks now I have noticed this bug. There are no new nubers in the Taskbar, only "NUL". Then a warning pops up, containig the text "Critical Low Glucose Alert". No matter what my real Dexcom nubers say. Sometimes it happens a few times in a row, every ~minute, sometimes it just works as intended. 

Restarting the .exe only works for a few minutes.

Im on Windows 11 and my Dexcom G7 mg/dl Data is from non US Servers.

![grafik](https://github.com/Delubear/GlucoseTray/assets/101606403/09f18a71-fb6f-49d8-89ec-573630a4d7ce)

**Comment by Delubear** [comment]
It woudn't be surprising if they changed some stuff with the G7.  Since I don't use the G7, I can't troubleshoot it directly, but I will see what I can find out.

In the meantime, you may be able to try the Nightscout implementation, if you're not already, and pull your readings from Nightscout rather than Dexcom.

**Comment by Delubear** [comment]
Could you try version 14.4.0?  I've made some logic adjustments so results of 0 (usually from response failure), will no longer trigger alerts.

https://github.com/Delubear/GlucoseTray/releases/tag/14.4.0

**Comment by derTheo01** [comment]
Thank you! Now it works exactly like you said: No low glucose alert when there is no new data.
